runtime: nodejs18  # Assurez-vous que cette version correspond à celle que vous utilisez.
env: standard
instance_class: F1  # Utilise la classe d'instance la moins chère.

manual_scaling:
  instances: 1  # Garde toujours une instance en cours d'exécution.

# Configuration des variables d'environnement de votre application.
env_variables:
  NODE_ENV: 'production'
  DISCORD_TOKEN: $DISCORD_TOKEN
