apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot-container
          image: eu.gcr.io/third-campus-417718/bot-discord:latest
          ports:
            - containerPort: 80
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DISCORD_TOKEN
            - name: NO_COLOR
              valueFrom:
                configMapKeyRef:
                  name: discord-bot-config
                  key: NO_COLOR
