name: CI/CD Workflow

on:
  push:
    branches: [ master ]  # Déclenche le workflow sur les push vers la branche master
  pull_request:
    branches: [ master ]  # Déclenche le workflow sur les pull requests vers la branche master

jobs:
  build:
    runs-on: ubuntu-latest  # Exécute le job sur la dernière version d'Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Récupère le code du dépôt

      - uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        with:
          app_yaml_path: "app.yaml"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Spécifiez la version de Node.js

      - name: Install Dependencies
        run: npm install  # Installe les dépendances de votre projet

      - name: Run Tests
        run: npm run test  # Remplacez par votre commande de test

      - name: Build
        run: npm run build  # Construit votre projet, si nécessaire

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Google Cloud
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
