name: Deploy to GKE

on:
  push:
    branches:
      - master  # Déclenche le workflow sur les push vers la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0  # Utilisez la dernière version disponible
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "gke-gcloud-auth-plugin" # Si nécessaire

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/bot-discord:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/bot-discord:latest

#      - name: Set up kubectl
#        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --region ${{ secrets.GKE_REGION }} --project ${{ secrets.GKE_PROJECT }}

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment/deployment.yaml

#      - name: Deploy to GKE
#        run: |
#          kubectl set image deployment/discord-bot-deployment discord-bot-container=gcr.io/${{ secrets.GCP_PROJECT_ID }}/bot-discord:latest